version: '3.7'
services:

    php:
        build:
            context: .
            target: php_app_dev
            dockerfile: ./docker/Dockerfile
        image: recruitment_app:${BUILD_TAG:-latest}
        environment:
            TZ: "${DOCKER_TZ:-Europe/Warsaw}"
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: "${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-on}"
